const SPOTIFY_API_BASE = 'https://api.spotify.com/v1';

class SpotifyApiError extends Error {
  constructor(status, message, details) {
    super(message);
    this.status = status;
    this.details = details;
  }
}

async function spotifyFetch(path, accessToken, options = {}) {
  const res = await fetch(`${SPOTIFY_API_BASE}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new SpotifyApiError(
      res.status,
      data?.error?.message || `Spotify API error (${res.status})`,
      data
    );
  }
  return data;
}

export async function searchTrack(query, accessToken) {
  const res = await fetch(
    `${SPOTIFY_API_BASE}/search?q=${encodeURIComponent(query)}&type=track&limit=1`,
    {
      headers: { Authorization: `Bearer ${accessToken}` },
    },
  );
  if (!res.ok) throw new Error("Search failed");
  const data = await res.json();
  return data.tracks.items[0] || null;
}

export async function getSpotifyProfile(accessToken) {
  return spotifyFetch('/me', accessToken);
}

// keep userId optional; use /me/playlists to avoid user-id mismatch issues
export async function createPlaylist(userId, name, accessToken) {
  return spotifyFetch('/me/playlists', accessToken, {
    method: 'POST',
    body: JSON.stringify({
      name: name || 'Mood Playlist',
      public: false,
      description: 'Generated by Mood Playlist Generator',
    }),
  });
}

export async function addTracksToPlaylist(playlistId, uris, accessToken, position) {
  if (!Array.isArray(uris) || uris.length === 0) {
    throw new Error('No track URIs provided');
  }

  const chunks = [];
  for (let i = 0; i < uris.length; i += 100) {
    chunks.push(uris.slice(i, i + 100));
  }

  const snapshotIds = [];
  for (let i = 0; i < chunks.length; i++) {
    const payload = i === 0 && Number.isInteger(position)
      ? { uris: chunks[i], position }
      : { uris: chunks[i] };

    const data = await spotifyFetch(`/playlists/${playlistId}/items`, accessToken, {
      method: 'POST',
      body: JSON.stringify(payload),
    });

    if (data?.snapshot_id) snapshotIds.push(data.snapshot_id);
  }

  return { snapshotIds };
}
